### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai201-kebap#11]
https://drive.google.com/file/d/1JyDN82JcLyx0T7sfTc0DpPWHgLITt2Rg/view?usp=sharing

**Comment by Dima-Kebap** [comment]
1 Завдання 
Танці
Зрозумілість: кожен розуміє що таке танці, та як їх використовувати
Цінність: навчитися танцям можна абсолютно безкоштовно
Актуальність: танцювати можна завжди: хоч у 3 роки, хоч у 60

2 Завдання
Мета: Потреба у підтриманні психологічно-емоціональної стабільності під час пиття води після танців з друзями
 1. Авторизація: авторизувати користувача у додатку, щоб наблизитись до мети тим, що він допомогає користувачеві отримати доступ до можливостей програмного продукту
 2. Написання online-повідомлення: дозволяє користувачу спілкуватися з друзями
 3. Підтвердження замовлення: дозволяє користувачу замовити воду для її пиття

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
